<?php
/**
 * Created by PhpStorm.
 * User: peflyn
 * Date: 06/06/17
 * Time: 11:58
 */

namespace Tests\AppBundle\Controller;


use Symfony\Bundle\FrameworkBundle\Client;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Tests\AppBundle\ControllerTest;

class CategoryControllerTest extends ControllerTest
{
    public static function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function testCreate(){
       $this->setUp();
    }

    public function testRead(array $category){
        $client = static::createClient();
        $crawler = $client->request();
    }

    /**
     * @param array $category
     */
    function testUpdate(array $category)
    {
        // TODO: Implement testUpdate() method.
    }

    function testDelete(array $category)
    {
        // TODO: Implement testDelete() method.
    }

}
