appbundle_get_questions:
    path:     /questions
    defaults:
        _controller: AppBundle:QuestionController:getQuestions

appbundle_get_question:
    path:  /question{id}
    defaults:
        _controller: AppBundle:QuestionController:getQuestion
    requirements:
        id: \d+