api_quiz_category:
    resource: '@AppBundle/Resources/config/routing/category.yml'

api_quiz_mode:
    resource: '@AppBundle/Resources/config/routing/mode.yml'

api_quiz_question:
    resource: '@AppBundle/Resources/config/routing/question.yml'

api_quiz_propositon:
    resource: '@AppBundle/Resources/config/routing/proposition.yml'

api_quiz_quiz:
    resource: '@AppBundle/Resources/config/routing/quiz.yml'

api_quiz_user:
    resource: '@AppBundle/Resources/config/routing/user.yml'
